version: 2

project_name: platform-doctor-cli

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: doctor
    main: ./cmd/doctor
    binary: doctor

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64

    ldflags:
      - >-
        -s -w
        -X github.com/gopher-opsx/platform-doctor-cli/internal/buildinfo.Version={{.Version}}
        -X github.com/gopher-opsx/platform-doctor-cli/internal/buildinfo.Commit={{.Commit}}
        -X github.com/gopher-opsx/platform-doctor-cli/internal/buildinfo.Date={{.Date}}

archives:
  - formats:
      - tar.gz

    format_overrides:
      - goos: windows
        formats:
          - zip

    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc